
#TODO: AS I DONT UNDERSTAND AT ALL ROS FRAME WORK I DO NOT KNOW IF ALL CAN BE DONE IN A SINGLE FILE
#?Depending the progress and my knowledge in ROS following days this could have more modules to do
#? See the teleop.py for how they publish values and all and everything
#TODO: DETERMINE THE TOPIC FOR PROVIDE THIS INFO

#TODO: NAGA
#*Publisher Node-> I understood it should publish into the topic the array generated by the function in robot_commands_path
#TODO: GAURAV
#*Susbcriber node-> I understood it should receive the info published in the topic to properly sent it to the robot-gazebo
#TODO: JONATHAN
#* set any configurations and steps to deploy, testing everything together with gazebo